### PR TITLE
Fix double-parenthesis in string representation

### LINKED ISSUE #94: Not.to_string() conversion has unneeded double-parenthesis if the inner expression is a binary operator
### 👓 What did you see?

If a tag-expression contains a `not` operator that encapsulate a binary operator (`and`, `or`),
the string conversion currently leads to double-parenthesis (unnecessary tautology).
This makes the textual string less readable and understandable.

EXAMPLE:

```yaml
# SOURCE: testdata/parsing.yml
# HINT: This data or similar examples are currently missing

- expression: 'not (a and b)'
  formatted.currently: 'not ( ( a and b ) )'
  formatted.should_be: 'not ( a and b )'
```

REASONS:

* The binary operators put already parenthesis around their boolean expression during string conversion
* If the `not` operator does the same (as it currently is implemented), we get two groups of parenthensis

AFFECTED:

* ALL tag-expression implementations

### ✅ What did you expect to see?

Only one parenthesis grouping, like the `formatted.should_be` case shown in the example above.

### 📦 Which tool/library version are you using?

I added additional case to the `testdata/parsing.yml` in my local workspace and run Java, Javascript and Go implementations.
Each failed the new additional tests.
The non-tested implementations (Ruby and Perl) are also be affected (as expected), by inspection of their implementation.

### 🔬 How could we reproduce it?

Add the following test-data items to `testdata/parsing.yml`:

```yaml
# SOURCE: testdata/parsing.yml

# BAD_EXAMPLES (how the string output currently is):

- expression: 'not (a and b)'
  formatted: 'not ( ( a and b ) )'
- expression: 'not (a or b)'
  formatted: 'not ( ( a or b ) )'
- expression: 'not (a and b) and c or not (d or f)'
  formatted: '( ( not ( ( a and b ) ) and c ) or not ( ( d or f ) ) )'

# GOOD_EXAMPLES (how the output should be):

- expression: 'not (a and b)'
  formatted: 'not ( a and b )'
- expression: 'not (a or b)'
  formatted: 'not ( a or b )'
- expression: 'not (a and b) and c or not (d or f)'
  formatted: '( ( not ( a and b ) and c ) or not ( d or f ) )'
```

0. Update the local workspace to the current HEAD of the GitHub:/cucumber/tag-expression repository.
1. Patch the testdata file
2. Run the tests for each implementation

### 📚 Any additional context?

Nope.

### PR DESCRIPTION
**Pull request by jenisys**
IMPLEMENTED FIX FOR:

* [x] java
* [x] javascript
* [x] python
* [x] go
* [x] perl
* [x] ruby

### 🤔 What's changed?

Fixes: #94 .

* Basically the `Not.to_string()` (name varies slightly depending on the programming language) conversion detects now if it contains a binary operator or not.

### ⚡️ What's your motivation? 

Make the output more readable, understandable and comparable to the textual input of the tag-expression.

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### ♻️ Anything particular you want feedback on?

The test case examples in the testdata files were not dense enough (not enough coverage, I think).
Otherwise, this problem should have surfaced already earlier.

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [=] UNCLEAR (if needed): My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

### CODE REVIEW

File: go/parser.go [hunk 1]
```diff
@@ -13,6 +13,7 @@ const OPERATOR = "operator"
 type Evaluatable interface {
 	Evaluate(variables []string) bool
 	ToString() string
+	IsBinaryOperator() bool
```
Comment (mpkorstanje) [inline go/parser.go:16]: I see that you've used two different solutions. You are either type checking against the struct/class/ect type. Or you've added an interface. Unfortunately I think this method now becomes part of the public API. Is there a way to avoid this?

Comment (mpkorstanje) [reply go/parser.go:16]: It might be as simple as using `isBinaryOperator` instead.

Comment (jenisys) [reply go/parser.go:16]: I know (but I did not add an interface that I am aware of; I just extended the existing interface).
But it was much simpler than to dive into these languages and find out if they provide an `is-instance-of(Class)` mechanism and how it works.

* Come up with a better approach that uses `is-instance-of(Class)` in Go, Perl, … and I am happy to change it
* Provide me with a better solution that does not expose the method `isBinaryOperator()` to an out-of-module user and allows to use this method within the module.

Comment (mpkorstanje) [reply go/parser.go:16]: Not tested.

Go: You can test if `x` is an instance of `y` with `x.(y)`

https://stackoverflow.com/a/72195588/3945473

Perl: You can use `isa`.

https://stackoverflow.com/a/1731655/3945473

File: go/parser.go [hunk 2]
```diff
@@ -220,6 +220,12 @@ func (a *andExpr) ToString() string {
 	return fmt.Sprintf("( %s and %s )", a.leftExpr.ToString(), a.rightExpr.ToString())
 }
 
+func IsBinaryOperator(e Evaluatable) bool {
```
Comment (mpkorstanje) [inline go/parser.go:223]: Go exports functions that start with a capital letter. Changing it to lowercase will solve that.

Comment (jenisys) [reply go/parser.go:223]: Thanks for the info.
DONE.

File: go/parser.go (hunk 1 above)
Comment (jenisys) [reply go/parser.go]: Thanks for the info.

**Review by mpkorstanje — APPROVED** [review]
LGTM. 

I will leave this open as a marker. Release on Thursday pending availability.
